server:
  port: 8085

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yyzd?serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl